apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quadrant-vms.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "quadrant-vms.labels" . | nindent 4 }}
data:
  ENABLE_STATE_STORE: {{ .Values.coordinator.env.ENABLE_STATE_STORE | quote }}
  CLUSTER_ENABLED: {{ .Values.coordinator.env.CLUSTER_ENABLED | quote }}
  ORPHAN_CLEANUP_INTERVAL_SECS: {{ .Values.coordinator.env.ORPHAN_CLEANUP_INTERVAL_SECS | quote }}
