{{- if .Values.rbac.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coordinator
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "quadrant-vms.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quadrant-vms-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "quadrant-vms.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coordinator-role
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "quadrant-vms.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coordinator-binding
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "quadrant-vms.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coordinator-role
subjects:
- kind: ServiceAccount
  name: coordinator
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quadrant-vms-service-role
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "quadrant-vms.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quadrant-vms-service-binding
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "quadrant-vms.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quadrant-vms-service-role
subjects:
- kind: ServiceAccount
  name: quadrant-vms-service
  namespace: {{ .Values.global.namespace }}
{{- end }}
