{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "quadrant-vms.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "quadrant-vms.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "quadrant-vms.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
