version: "3.9"
services:
  minio:
    image: minio/minio:latest
    command: ["server","/data"]
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
  # nats:
  #   image: nats:2
  #   command: ["-js"]
  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_PASSWORD: vms
  #     POSTGRES_DB: vms
  #   ports: ["5432:5432"]
  # api-gateway:
  #   image: ghcr.io/yourorg/api-gateway:dev
  #   depends_on: [nats, minio, postgres]
  # ingest-node:
  #   image: ghcr.io/yourorg/ingest-node:dev
  #   depends_on: [api-gateway]
  # pipeline-node:
  #   image: ghcr.io/yourorg/pipeline-node:dev
  # recorder-node:
  #   image: ghcr.io/yourorg/recorder-node:dev
